### PR TITLE
added typing to SCPIDevice class for all methods until `setStepSize`

### PR DESCRIPTION
**Pull request by ilka-schulz**
I added some type annotations and `# TODO: ...` comments but only for the `SCPIDevice` class and only for the first 1357 lines (until `setStepSize`). Also some additional code, e.g. a method which returns the device timestamp as `datetime` struct, not as `str`.

I would appreciate some feedback whether my annotations make sense.

### CODE REVIEW

**Comment by maxkrapp1** [comment]
Your additions to the documentation and the refactoring are very good.
Here we are happy about any feedback.

You have added [class attributes](https://docs.python.org/3/tutorial/classes.html#class-objects) these are not necessary, because you can only use the member attributes, because the classes are not allowed to share these attributes.

**Comment by ilka-schulz** [comment]
> You have added [class attributes](https://docs.python.org/3/tutorial/classes.html#class-objects) these are not necessary, because you can only use the member attributes, because the classes are not allowed to share these attributes.

I already guessed that these should be private fields but I ignored the visibility of the fields for now ;) Afaik, the proper way to make a an attribute private in Python is to start it with an underscore or use dunderscores. You already start the attributes with an underscore which sends the user the signal not to alter these fields.

[This StackOverflow answer](https://stackoverflow.com/questions/14671487/what-is-the-difference-in-python-attributes-with-underscore-in-front-and-back) cites the [naming conventions in PEP 8](https://peps.python.org/pep-0008/#naming-conventions), specifically [Descriptive Naming Styles](https://peps.python.org/pep-0008/#descriptive-naming-styles). I try to write by the rules listed in PEP (specifically the last link), so I declared them, leaving them starting with and underscore.

I think it would be best to leave the attribute declarations in the code. They make the development process much easier as they give an overview over the attributes both to the user and the auto-completion.

If you like, you can merge the PR or change it as you wish. I probably do not have the time right now to continue adding type annotations and I guess there is no sense in letting the PR dangle.

**Comment by maxkrapp1** [comment]
I must apologize for my criticism, your changes were all correct. I hadn't dealt with variable annotations very much, and misinterpreted your changes.

According to [PEP 526](https://peps.python.org/pep-0526/#class-and-instance-variable-annotations) your changes are perfectly correct, and you have created uninitialized instance variables with these changes.

Thanks for partially adding the type annotations, I will complete this.

**Comment by ilka-schulz** [comment]
Thanks for merging!

And don't apologize; I am new to Python myself :wink:

**Pull request merged**
